name: 🐛 Bug / Crash Report
description: File a bug / crash report
title: "[Bug]: "
labels: [bug, crash]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: general-info
    attributes:
      label: General Info
      description: You may select more than one.
      options:
        - label: I can reproduce this issue consistently in single-player
        - label: I can reproduce this issue consistently in multi-player
        - label: I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
          required: true
        - label: I am crashing and can provide my crash report(s)
        - label: I am using the latest version of the mod
  - type: input
    id: patchline
    attributes:
      label: Game Patchline
      placeholder: ex. release
      description: What patchline are you playing on? (release, pre-release)
    validations:
      required: false
  - type: input
    id: mod-info
    attributes:
      label: Mod version
      placeholder: ex. 0.0.1
      description: Please be as specific as possible, latest is not a valid version
    validations:
      required: true
  - type: input
    id: java-info
    attributes:
      label: Java version
      placeholder: ex. OpenJDK 25.0.1
      description: Please be as specific as possible, latest is not a valid version
    validations:
      required: true
  - type: textarea
    id: installed-mods
    attributes:
        label: Installed Mods
        description: Please list all installed mods and their versions. If you have a large number of mods, please provide a link to a Pastebin or similar.
        placeholder: List your mods here or provide a link to a Pastebin or similar.
    validations:
      required: false
  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Additional Information
      description: Please post any crash reports, screenshots, etc. here. (use Pastebin or similar for large logs)
      placeholder: Please put crash reports onto Pastebin or other paste services and link them here.
    validations:
      required: false
